import type { ThemeBanks } from "./types";

/**
 * English line banks, hand-written, per theme — mirrors wordbanks.fr.ts in
 * structure and mood. Haiku syllable counts (5/7/5) are kept close but,
 * as with the French bank, treated as a poetic convention rather than a
 * strict phonetic rule. See README.
 */
export const wordBanksEn: ThemeBanks = {
  tendre: {
    haiku5: [
      "Your hand finds my hand",
      "A soft golden hush",
      "The curve of your neck",
      "Barely a whisper",
      "A gentle small touch",
      "Just one clear, calm look",
    ],
    haiku7: [
      "The light rests soft on your cheek",
      "The quiet between our hands",
      "A coffee shared between two",
      "Your laugh against my shoulder",
      "Tenderness says nothing here",
      "Too big a sweater for cold",
    ],
    versLibre: {
      ouverture: [
        "There is, in this morning, a softness with no name.",
        "You are sitting there, and everything slows down.",
        "Between us, something simple and warm.",
        "Tenderness always begins with a silence.",
        "We said nothing, but everything was there.",
      ],
      milieu: [
        "Your hand finds mine without even thinking.",
        "The sweater you wear still smells of sleep.",
        "A warmth stays on my skin, unhurried.",
        "One smile is enough to change the light.",
        "We look outside, but we only see us.",
        "Nothing is urgent, this morning belongs to no one.",
        "Words become unnecessary, almost too much.",
        "You laugh softly, and the world slows down.",
        "A cup still warm between our two hands.",
        "Time stretches out like a cat on the couch.",
      ],
      cloture: [
        "And that's all. That's already so much.",
        "We stay there, not wanting to leave.",
        "Tenderness needs no further word.",
        "So little was ever enough.",
        "We simply call it being well.",
      ],
    },
    couplets: [
      ["Your hand settles, a gesture so light,", "and nothing else exists tonight."],
      ["The evening light falls soft and slow,", "it settles like a prayer we know."],
      ["Tonight the dark will feel so kind,", "by candlelight, hand laced with mine."],
      ["Deep in the hollow of your care,", "I finally set my worry there."],
      ["I know each line upon your face,", "soft as a morning free of haze."],
      ["Your hand in mine, a quiet thread,", "there's nothing more I need instead."],
    ],
  },
  melancolique: {
    haiku5: [
      "Rain against the glass",
      "A little silence",
      "Time slowly fading",
      "One chair sitting empty",
      "Autumn settles in",
      "Only shades of grey",
    ],
    haiku7: [
      "The leaves fall without a sound",
      "A letter never once sent",
      "The coffee cools on its own",
      "We think of those who have gone",
      "The sky still keeps its regrets",
      "A memory lingers still",
    ],
    versLibre: {
      ouverture: [
        "Some days everything seems a little greyer.",
        "The rain falls, and with it, something drifts away.",
        "We think of what we didn't say in time.",
        "The silence tonight tastes like something missing.",
        "Something went quiet, softly, without a sound.",
      ],
      milieu: [
        "The window still holds the trace of fog.",
        "We reread a letter we can no longer send.",
        "The coffee went cold and no one noticed.",
        "Objects remember better than we do.",
        "A song comes back, and with it, a face.",
        "We search for a scent that has faded away.",
        "Time doesn't heal, it only covers over.",
        "One empty chair remains at the table.",
        "We watch leave what we never learned to keep.",
        "Even the silence has a color, tonight.",
      ],
      cloture: [
        "And yet, we carry on.",
        "We close the window, quietly.",
        "Only this taste of grey and tender remains.",
        "We learn to live with the absence.",
        "That too is love: to keep the trace.",
      ],
    },
    couplets: [
      ["The rain falls down, the light grows dim,", "and I think of you, with hope grown thin."],
      ["What's left behind is quiet, bare,", "a little longing, a little care."],
      ["The sky today is darker still,", "regrets that gather at their will."],
      ["A photograph a little worn,", "from some season already gone."],
      ["There are the ones who went away,", "and that same void that seemed to stay."],
      ["The city sits a little grey,", "carried off by wind astray."],
    ],
  },
  reveur: {
    haiku5: [
      "The clouds drift slowly",
      "A sky made of wool",
      "The moon lingers still",
      "Floating with no weight",
      "A soft passing dream",
      "The stars gently blink",
    ],
    haiku7: [
      "We drift between two soft dreams",
      "The sky is covered in velvet",
      "The night invents its own roads",
      "We float above the real world",
      "The stars are weaving a map",
      "Sleep opens a quiet door",
    ],
    versLibre: {
      ouverture: [
        "There is a place between waking and sleep.",
        "The sky tonight looks like a promise.",
        "We close our eyes, and already we drift.",
        "Somewhere, a door opens onto the imagined.",
        "The real world fades, softly.",
      ],
      milieu: [
        "The clouds trace roads we will never follow.",
        "We float among the stars, unhurried.",
        "The moon lights a path no one else knows.",
        "Time barely means anything here.",
        "We invent whole worlds just to live in them.",
        "The silence becomes a calm, quiet ocean.",
        "Something gentle carries us off, without a sound.",
        "We forget where the dream starts and the day ends.",
        "The colors blend like a watercolor.",
        "We walk upon a cloud and never fall.",
      ],
      cloture: [
        "And we let ourselves be carried, without resisting.",
        "The dream goes on, even with eyes open.",
        "We hold this dream a little longer, before returning.",
        "That's where we feel truly light.",
        "We close our eyes again, just a little more.",
      ],
    },
    couplets: [
      ["We rise up slowly on a cloud,", "no destination, just a shroud."],
      ["The night puts on a single star,", "and turns the sky into a sail so far."],
      ["We drift so softly into dream,", "just before the morning's gleam."],
      ["The moon shines down without a sound,", "a lost path in the mist unwound."],
      ["The wind is whispering outside,", "while the whole city drifts and sighs."],
      ["We watch the sky a moment still,", "and let the real world lose its will."],
    ],
  },
  lumineux: {
    haiku5: [
      "The sun rises now",
      "A morning brand new",
      "The light comes pouring",
      "A little of hope",
      "The day starts anew",
      "All feels possible",
    ],
    haiku7: [
      "The sunlight warms up the whole room",
      "A morning full of promises",
      "The light dances on the ceiling",
      "We breathe in air that feels lighter",
      "The spring pushes through the window",
      "Everything turns simple and clear",
    ],
    versLibre: {
      ouverture: [
        "This morning, the light walks in without knocking.",
        "There is something new in the air.",
        "The sun rises like a promise kept.",
        "We open the shutters on a day that starts well.",
        "Something is brightening, softly, within us.",
      ],
      milieu: [
        "The light crosses the room and touches all it finds.",
        "We breathe a little wider, this morning.",
        "The coffee tastes like good days ahead.",
        "The curtains move with a gentle wind.",
        "Something lightens, though we don't know why.",
        "We feel like smiling for no clear reason.",
        "The world seems a little simpler, today.",
        "The day opens like an outstretched hand.",
        "We can sense something good beginning.",
        "Even the shadows seem softer.",
      ],
      cloture: [
        "And we move on, carried by this new day.",
        "We hold onto this light a little longer.",
        "It's a morning that makes you want to stay.",
        "Just a little sun, and all is well.",
        "We let ourselves be carried by this brightness.",
      ],
    },
    couplets: [
      ["The morning opens like a gentle sigh,", "carried by rays down from the sky."],
      ["Upon the rooftops joy will land,", "as light as silk laid on the hand."],
      ["We breathe in air entirely new,", "the day breaks bright, the sky is true."],
      ["This morning carries hope so near,", "and all the light seems dancing clear."],
      ["The day breaks bright, the day breaks true,", "and everything feels lighter too."],
      ["A sky so new, a sky so fair,", "announces days beyond compare."],
    ],
  },
  apaisant: {
    haiku5: [
      "A warm woolen throw",
      "The silence feels soft",
      "One book left open",
      "Nothing to rush here",
      "The candle flickers",
      "Time begins to slow",
    ],
    haiku7: [
      "The rain falls behind the window",
      "The tea steams inside the warm cup",
      "We wrap ourselves in the silence",
      "A book is waiting on the table",
      "The candle barely gives its light",
      "Nothing rushes, all is calm now",
    ],
    versLibre: {
      ouverture: [
        "Outside it rains, but here all is calm.",
        "We settle in, and time loses its schedule.",
        "The throw, the warm cup, the silence: it's all here.",
        "There are afternoons made for doing nothing.",
        "We close the door, and the world stays outside.",
      ],
      milieu: [
        "The tea steams gently on the low table.",
        "We wrap ourselves in a blanket too large.",
        "The rain taps softly against the window.",
        "A book rests, open, on our lap.",
        "The candle trembles a little, for no reason.",
        "We hear only the soft sound of turning pages.",
        "Nothing is urgent, no one is waiting.",
        "The silence, here, feels almost like company.",
        "We breathe slowly, without thinking about it.",
        "Time, too, sits down in the armchair.",
      ],
      cloture: [
        "And we stay there, not wanting to move.",
        "That was exactly what today needed.",
        "We close our eyes, for a moment, at peace.",
        "Nothing more is needed.",
        "This moment alone is enough.",
      ],
    },
    couplets: [
      ["The tea is steaming in its cup,", "set on the low table, all cozied up."],
      ["The candle softly starts to sway,", "in such a quiet room today."],
      ["A blanket soft and warm as down,", "rests upon my lap, all around."],
      ["Here we no longer wait for a thing,", "and yet all is well, everything."],
      ["A good book waits to be pursued,", "and nothing else need be construed."],
      ["It rains outside, the skies are grey,", "but here inside, comfort will stay."],
    ],
  },
};
