import type { ThemeBanks } from "./types";

/**
 * Banques de vers en français, écrites à la main, par thème. Les comptes
 * de syllabes des haïkus (5/7/5) sont approximatifs — convention courante
 * chez de nombreux haïkistes francophones plutôt que règle phonétique
 * stricte (le français ne se prête pas aussi bien que le japonais au
 * compte de mores). Voir README.
 */
export const wordBanksFr: ThemeBanks = {
  tendre: {
    haiku5: [
      "Ta main dans la mienne",
      "Un souffle léger",
      "Le creux de ton cou",
      "Presque un murmure",
      "Un geste très doux",
      "Rien qu'un regard clair",
    ],
    haiku7: [
      "La lumière sur ta joue",
      "Le silence entre nos mains",
      "Un café partagé à deux",
      "Ton rire contre mon épaule",
      "La tendresse ne dit rien",
      "Un pull trop grand pour l'hiver",
    ],
    versLibre: {
      ouverture: [
        "Il y a dans ce matin une douceur qui ne dit pas son nom.",
        "Tu es assise là, et tout devient plus lent.",
        "Entre nous, quelque chose de simple et de chaud.",
        "La tendresse commence toujours par un silence.",
        "On n'a rien dit, mais tout était là.",
      ],
      milieu: [
        "Ta main trouve la mienne sans même y penser.",
        "Le pull que tu portes sent encore le sommeil.",
        "Il y a une chaleur qui reste sur ma peau.",
        "Un sourire suffit à changer la lumière.",
        "On regarde dehors, mais on ne voit que nous.",
        "Rien ne presse, ce matin appartient à personne.",
        "Les mots deviennent inutiles, presque encombrants.",
        "Tu ris doucement, et le monde ralentit.",
        "Une tasse encore chaude entre nos deux mains.",
        "Le temps s'étire comme un chat sur le canapé.",
      ],
      cloture: [
        "Et c'est tout. C'est déjà beaucoup.",
        "On reste là, sans vouloir partir.",
        "La tendresse n'a pas besoin d'un mot de plus.",
        "Il suffisait de si peu.",
        "On appelle ça, simplement, être bien.",
      ],
    },
    couplets: [
      ["Ta main se pose, un geste doux,", "et plus rien n'existe entre nous."],
      ["La lumière du soir est légère,", "elle se pose comme une prière."],
      ["Ce soir la nuit sera belle,", "à la lueur d'une chandelle."],
      ["Dans le creux de ta douceur,", "je pose enfin mon cœur."],
      ["Je connais chaque trait de ton visage,", "doux comme un matin sans nuage."],
      ["Ta main dans la mienne est un lien,", "je ne veux plus d'autre bien."],
    ],
  },
  melancolique: {
    haiku5: [
      "La pluie sur la vitre",
      "Un peu de silence",
      "Le temps qui s'efface",
      "Une chaise vide",
      "L'automne s'installe",
      "Rien qu'un peu de gris",
    ],
    haiku7: [
      "Les feuilles tombent sans un bruit",
      "Une lettre jamais postée",
      "Le café refroidit tout seul",
      "On pense à ceux qui sont partis",
      "Le ciel garde ses regrets",
      "Un souvenir flotte encore là",
    ],
    versLibre: {
      ouverture: [
        "Il y a des jours où tout semble un peu plus gris.",
        "La pluie tombe, et avec elle, quelque chose s'en va.",
        "On pense à ce qu'on n'a pas dit à temps.",
        "Le silence, ce soir, a un goût de manque.",
        "Quelque chose s'est éteint, doucement, sans bruit.",
      ],
      milieu: [
        "La fenêtre garde la trace de la buée.",
        "On relit une lettre qu'on ne peut plus envoyer.",
        "Le café a refroidi sans que personne n'y touche.",
        "Les objets se souviennent mieux que nous.",
        "Une chanson revient, et avec elle, un visage.",
        "On cherche encore une odeur qui s'est effacée.",
        "Le temps ne répare pas, il recouvre, simplement.",
        "Il reste une chaise vide à la table.",
        "On regarde partir ce qu'on n'a pas su garder.",
        "Même le silence a une couleur, ce soir.",
      ],
      cloture: [
        "Et pourtant, on continue.",
        "On referme la fenêtre, doucement.",
        "Il ne reste que ce goût de gris et de tendre.",
        "On apprend à vivre avec l'absence.",
        "C'est ça aussi, aimer : garder la trace.",
      ],
    },
    couplets: [
      ["La pluie tombe, il commence à faire soir,", "et je pense à toi sans espoir."],
      ["Ce qui reste, c'est le silence,", "un peu de manque, un peu d'absence."],
      ["Le ciel aujourd'hui est plus sombre,", "et les regrets se comptent sans nombre."],
      ["Une photo un peu fanée,", "d'une saison déjà passée."],
      ["Il y a ceux qui sont partis,", "et ce vide qu'on a tant senti."],
      ["La ville est un peu grise,", "portée par une brise."],
    ],
  },
  reveur: {
    haiku5: [
      "Les nuages passent",
      "Un ciel de coton",
      "La lune s'attarde",
      "Flotter sans effort",
      "Un songe léger",
      "Les étoiles clignent",
    ],
    haiku7: [
      "On dérive entre deux rêves",
      "Le ciel se couvre de velours",
      "La nuit invente des chemins",
      "On flotte au-dessus du réel",
      "Les étoiles tissent une carte",
      "Le sommeil ouvre une porte",
    ],
    versLibre: {
      ouverture: [
        "Il y a un endroit entre veille et sommeil.",
        "Le ciel, ce soir, ressemble à une promesse.",
        "On ferme les yeux, et déjà on s'envole.",
        "Quelque part, une porte s'ouvre sur l'imaginaire.",
        "Le monde réel s'efface, doucement.",
      ],
      milieu: [
        "Les nuages dessinent des routes qu'on ne suivra jamais.",
        "On flotte entre les étoiles sans se presser.",
        "La lune éclaire un chemin que personne ne connaît.",
        "Le temps n'a plus vraiment de sens, ici.",
        "On invente des mondes juste pour les habiter.",
        "Le silence devient un océan tranquille.",
        "Quelque chose de doux nous emporte, sans bruit.",
        "On oublie où commence le rêve, où finit le jour.",
        "Les couleurs se mélangent comme une aquarelle.",
        "On marche sur un nuage sans jamais tomber.",
      ],
      cloture: [
        "Et on se laisse porter, sans résister.",
        "Le rêve continue, même les yeux ouverts.",
        "On garde ce songe encore un peu, avant de revenir.",
        "C'est là qu'on se sent vraiment léger.",
        "On referme les yeux, encore un peu.",
      ],
    },
    couplets: [
      ["On monte doucement sur un nuage,", "sans destination, juste un voyage."],
      ["La nuit s'habille d'une étoile,", "et le ciel devient une voile."],
      ["On glisse doucement dans un rêve,", "juste avant que le jour ne se lève."],
      ["La lune éclaire sans aucune,", "un chemin perdu dans la brume."],
      ["Le vent murmure dehors,", "pendant que la ville s'endort."],
      ["On regarde un instant le ciel,", "et on oublie le réel."],
    ],
  },
  lumineux: {
    haiku5: [
      "Le soleil se lève",
      "Un matin tout neuf",
      "La lumière entre",
      "Un peu d'espérance",
      "Le jour recommence",
      "Tout semble possible",
    ],
    haiku7: [
      "Le soleil réchauffe la pièce",
      "Un matin plein de promesses",
      "La lumière danse au plafond",
      "On respire un air plus léger",
      "Le printemps pousse la fenêtre",
      "Tout redevient simple et clair",
    ],
    versLibre: {
      ouverture: [
        "Ce matin, la lumière entre sans frapper.",
        "Il y a quelque chose de neuf dans l'air.",
        "Le soleil se lève comme une promesse tenue.",
        "On ouvre les volets sur un jour qui commence bien.",
        "Quelque chose s'éclaire, doucement, en nous.",
      ],
      milieu: [
        "La lumière traverse la pièce et touche tout ce qu'elle rencontre.",
        "On respire un peu plus large, ce matin.",
        "Le café a le goût des bonnes journées.",
        "Les rideaux bougent avec un vent tout doux.",
        "Quelque chose s'allège, sans qu'on sache pourquoi.",
        "On a envie de sourire sans raison précise.",
        "Le monde semble un peu plus simple, aujourd'hui.",
        "La journée s'ouvre comme une main tendue.",
        "On sent que quelque chose de bon commence.",
        "Même les ombres semblent plus douces.",
      ],
      cloture: [
        "Et on avance, portés par ce jour neuf.",
        "On garde cette lumière encore un peu.",
        "C'est un matin qui donne envie de rester.",
        "Rien qu'un peu de soleil, et tout va bien.",
        "On se laisse porter par cette clarté.",
      ],
    },
    couplets: [
      ["Le matin s'ouvre comme un réveil,", "porté par les rayons du soleil."],
      ["Sur les toits se pose la joie,", "légère comme un peu de soie."],
      ["On respire un nouvel air,", "le jour se lève, tout est clair."],
      ["Ce matin porte une espérance,", "et la lumière semble en danse."],
      ["Le jour se lève, lumineux,", "et tout paraît un peu plus heureux."],
      ["Un ciel tout neuf, un ciel si beau,", "annonce un jour, un jour nouveau."],
    ],
  },
  apaisant: {
    haiku5: [
      "Un plaid bien chaud",
      "Le silence est doux",
      "Un livre ouvert là",
      "Rien ne presse ici",
      "La bougie vacille",
      "Le temps ralentit",
    ],
    haiku7: [
      "La pluie tombe derrière la vitre",
      "Le thé fume dans la tasse chaude",
      "On s'enroule dans le silence",
      "Un livre attend sur la table",
      "La bougie éclaire à peine",
      "Rien ne presse, tout est calme",
    ],
    versLibre: {
      ouverture: [
        "Dehors il pleut, mais ici tout est calme.",
        "On s'installe, et le temps n'a plus d'horaire.",
        "Le plaid, la tasse chaude, le silence : tout est là.",
        "Il y a des après-midis faits pour ne rien faire.",
        "On ferme la porte, et le monde reste dehors.",
      ],
      milieu: [
        "Le thé fume doucement sur la table basse.",
        "On s'enroule dans une couverture trop grande.",
        "La pluie tape doucement contre la fenêtre.",
        "Un livre repose, ouvert, sur les genoux.",
        "La bougie tremble un peu, sans raison.",
        "On entend juste le bruit léger des pages.",
        "Rien ne presse, personne n'attend rien.",
        "Le silence, ici, est presque une compagnie.",
        "On respire lentement, sans y penser.",
        "Le temps s'assoit, lui aussi, dans le fauteuil.",
      ],
      cloture: [
        "Et on reste là, sans vouloir bouger.",
        "C'est exactement ce qu'il fallait, aujourd'hui.",
        "On referme les yeux, un instant, tranquille.",
        "Rien de plus n'est nécessaire.",
        "Ce moment-là suffit, entièrement.",
      ],
    },
    couplets: [
      ["Le thé fume dans une tasse,", "posée sur la table basse."],
      ["La bougie doucement vacille,", "dans une pièce si tranquille."],
      ["Un plaid tout doux,", "posé sur mes genoux."],
      ["Ici on n'attend plus rien,", "et pourtant tout va bien."],
      ["Un bon livre à suivre,", "et rien d'autre à poursuivre."],
      ["Il pleut, dehors,", "mais dedans, tout est confort."],
    ],
  },
};
